cloud:
  aws:
    credentials:
      access-key: AKIA53BN34G64OHIQRBI
      secret-key: xmQ75JumtYETUk9QdboamLfCz1nkSPMWf3kj7lcc
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: my-sample-shaliya


#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB

server:
  port: 9090
