cloud:
  aws:
    credentials:
      access-key: AKIA53BN34G6VHLDQMEB
      secret-key: UEwitfRe9Yj3EGZXpRizJCl/yxayafRanckixsRh
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: visco-image-upload-sample


#spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 5MB
#      max-request-size: 10MB

server:
  port: 9090
